version: '3.8'

services:
  acestream-scraper:
    image: visesa84/acestream-scraper-pyacexy:latest
    container_name: Acestream_Proxy
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    environment:
      - TZ=Europe/Madrid
      - ENABLE_TOR=false
      - ENABLE_ACEXY=true
      - ENABLE_ACESTREAM_ENGINE=true
      - ENABLE_WARP=false
      - WARP_LICENSE_KEY=
      - ACESTREAM_HTTP_PORT=6878
      - ACESTREAM_HTTP_HOST=ACEXY_HOST
      - FLASK_PORT=8040
      - ACEXY_LISTEN_ADDR=:8080
      - ACEXY_HOST=localhost
      - ACEXY_PORT=6878
      - ALLOW_REMOTE_ACCESS=no
      - ACEXY_NO_RESPONSE_TIMEOUT=15
      - ACEXY_BUFFER_SIZE=10
      - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2
      - MALLOC_CONF=dirty_decay_ms:1000,muzzy_decay_ms:1000
      - EXTRA_FLAGS="--cache-dir /tmp --cache-limit 2 --log-stderr --log-stderr-level error --max-connections 300 --max-peers 50 --core-dlrate-helper 0 --stats-report-interval 10 --live-cache-type memory --live-cache-size 209715200"

    ports:
      - "6878:6878"  # AceStream Engine Port 
      - "8040:8040"  # Flask application
      - "8080:8080"  # PyAcexy proxy
      - "8621:8621"  # Acestream P2P Port
      - "43110:43110"  # ZeroNet UI
      - "43111:43111"  # ZeroNet peer
      - "26552:26552"  # ZeroNet peer
    volumes:
      - ./data/zeronet:/app/ZeroNet/data
      - ./data/config:/app/config
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
