"""Add retry_start to recording_schedules

Revision ID: f6550830694d
Revises: 8a3349893ea2
Create Date: 2026-03-14 17:02:27.451388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6550830694d'
down_revision = '8a3349893ea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('recording_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retry_start', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
    
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('recording_schedules', schema=None) as batch_op:
        batch_op.drop_column('retry_start')

    # ### end Alembic commands ###
