name: Crear Release Solo Texto

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Crear GitHub Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          prerelease: ${{ contains(github.ref_name, 'beta') }}
          token: ${{ secrets.GITHUB_TOKEN }}
